---
# tasks file for aws-cloudwatch
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    state: present
    pkg:
    - unzip
    - libwww-perl
    - libdatetime-perl

- name: Unarchive scripts
  ansible.builtin.unarchive:
    src: {{ monitoring_url }}
    dest: /usr/local/bin
    copy: no

- name: Ensure aws monitoring user exists
  ansible.builtin.user:
    name: awsmon
    state: present

- name: Ensure disk monitoring cron job is enabled
  ansible.builtin.cron:
    user: awsmon
    name: 'disk-space-avail-{{ item }}'
    minute: '{{ monitoring_minute }}'
    hour: '{{ monitoring_hour }} '
    job: '/usr/local/bin/aws-scripts-mon/mon-put-instance-data.pl --from-cron --auto-scaling --disk-space-avail --disk-path={{ item }}'
  with_items: '{{ monitoring_paths }}'

- name: Ensure memory monitoring cron job is enabled
  ansible.builtin.cron:
    user: awsmon
    name: 'memory-available'
    minute: '{{ monitoring_minute }}'
    hour: '{{ monitoring_hour }}'
    job: '/usr/local/bin/aws-scripts-mon/mon-put-instance-data.pl --from-cron --auto-scaling --mem-avail'

- name: Ensure cache directory exists
  ansible.builtin.file:
    path: /var/tmp/aws-mon
    state: directory
    owner: awsmon

- name: Get all scripts in /usr/local/bin/aws-scripts-mon/
  ansible.builtin.find:
    paths: /usr/local/bin/aws-scripts-mon/
    file_type: file
    use_regex: true
    patterns:
      - "^.+.conf$"
  register: aws_mon_scripts

- name: Add executable permissions for scripts in /usr/local/bin/aws-scripts-mon
  ansible.builtin.file:
    path: "/usr/local/bin/aws-scripts-mon/{{ item }}"
    mode: "a+x"
  loop: "{{ aws_mon_scripts }}"
